INSERT INTO `usergroups` (`type`, `uid1`, `uid2`, `uid3`, `description`, `status`) VALUES

(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, 'Nominal', 1),
(2, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, 'Interacting', 1);

INSERT INTO `usergroups` (`type`, `uid1`, `uid2`, `uid3`, `uid4`, `description`, `status`) VALUES
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, NULL, 'Nominal', 2),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, NULL, 'Nominal', 2),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, NULL, 'Nominal', 2),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(2, NULL, NULL, NULL, NULL, 'Non-interacting', 1),
(3, NULL, NULL, NULL, NULL, 'Interacting', 1),
(1, NULL, NULL, NULL, NULL, 'Nominal', 2);

